dist: bionic   # required for Python >= 3.7
language: python
python:
  - "3.7"

deploy:
  provider: pypi
  username: __token__
  password:
    secure: J2drdgyMvGjLjtlUyS+BHAiiL5oDuRP7QS7+9axv2lC+Pt2RE+NaAFIn67ZNwRwh/1FSjlxSA246PTksRaG9H4leQvPbl+iDkELmFR4h970WkZuFFvhvKBlHjPobPHUI3Zl6dMBO3cX6padv5mm5mRIDcwG6LPUYuL6qOIp2NGX+cET0LAXPRnAPCjPXyVJSM0tnyzWmoLkYIXD7+bHu2ypoyRIGg2NlhP/rPZ7qBir34JH/eF7XZsfnI9Yr/u4NYJe6jkn0ZNu5U+YYzrGL5FieXG7PLC7VZa9Zh9XxT1WKglEu1nXp7SPrz2LiKnSZPTsP3VBdGygglD1zvCdE2LkfBCJh1GJfHSLGtcg6U8aZS299qOO47QiCCJkUCPbaIUul1Ih458GTAdF+XaTR06lhIBKvyEznl0YELQljzkyT8WxlYRMq9+g2XiU9X5wneOAygIrUkcCsFl/vxs1KW5W5vjwZFU8GZuKZGwyOIJ17esJ+mClrun4eancbvUe1hRe1E89DSGNv0ZbfrbTvrwNzYcu0s0pQA3rNmRyFmgOyYm/aw7Z/rhvjK6N/Tqbk8c1LiYUYe3OJys0oVdSRprGYJbSiat5zJiZPVnlkqEk0366eniurixedekcQSYGPOQOoQezGGf7zf4rbhs/VMOo0/Gxk9O/v02GoOdInf8A=
  
  distributions: "sdist bdist_wheel"
  on:
      branch: pip-package
