version: '3.1'

services:

  archivy:
    image: harshavardhanj/archivy
    ports:
      - "5000:5000"
    volumes:
      - archivyData:/usr/src/app/data
    environment:
      - FLASK_DEBUG=0
      - ELASTICSEARCH_ENABLED=0

volumes:
  archivyData:
