name: Automated tests on changes

on: 
  push:
    branches:
      - 'master'
    paths:
      - 'archivy/**'
      - '.github/workflows/pytest.yml'
  pull_request:
    paths:
      - 'archivy/**'
      - '.github/workflows/pytest.yml'

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: stefanzweifel/git-auto-commit-action@v4
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
        commit_message: Add dep to requirements
        file_pattern: requirements*.txt
    - name: Update requirements
      run: |
        pip install pigar
        pigar -P archivy/
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-tests.txt
    - name: Run tests
      run: |
        pytest tests/
        
